// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "RadminTableColumn.cs" with this contents:
/*
namespace AppCode.Extensions.Radmin.Data
{
  public partial class RadminTableColumn
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpTypedDataModelsGenerator
// App/Edition: App Ext Radmin/
// User:        2sic Web-Developer
using System.Text.Json.Serialization;
using ToSic.Sxc.Adam;

namespace AppCode.Extensions.Radmin.Data
{
  // This is a generated class for RadminTableColumn (scope: Extensions.Radmin)
  // To extend/modify it, see instructions above.

  /// <summary>
  /// RadminTableColumn data. <br/>
  /// Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.FieldFormat`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  /// <remarks>
  /// This Content-Type is NOT in the default scope, so you may not see it in the Admin UI. It's in the scope Extensions.Radmin.
  /// </remarks>
  public partial class RadminTableColumn: AutoGenerated.ZAutoGenRadminTableColumn
  {  }
}

namespace AppCode.Extensions.Radmin.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated *base* class for 'RadminTableColumn' in scope 'Extensions.Radmin'. It uses special names to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenRadminTableColumn: Custom.Data.CustomItem
  {
    /// <summary>
    /// FieldFormat as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("FieldFormat", scrubHtml: true) etc.
    /// </summary>
    public string FieldFormat => _item.String("FieldFormat", fallback: "");

    /// <summary>
    /// FieldTemplate as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("FieldTemplate", scrubHtml: true) etc.
    /// </summary>
    public string FieldTemplate => _item.String("FieldTemplate", fallback: "");

    /// <summary>
    /// FieldTooltip as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("FieldTooltip", scrubHtml: true) etc.
    /// </summary>
    public string FieldTooltip => _item.String("FieldTooltip", fallback: "");

    /// <summary>
    /// FieldValue as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("FieldValue", scrubHtml: true) etc.
    /// </summary>
    public string FieldValue => _item.String("FieldValue", fallback: "");

    /// <summary>
    /// FreezeColumn as bool. <br/>
    /// To get nullable use .Get("FreezeColumn") as bool?;
    /// </summary>
    public bool FreezeColumn => _item.Bool("FreezeColumn");

    /// <summary>
    /// HeaderTooltip as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("HeaderTooltip", scrubHtml: true) etc.
    /// </summary>
    public string HeaderTooltip => _item.String("HeaderTooltip", fallback: "");

    /// <summary>
    /// Hide as bool. <br/>
    /// To get nullable use .Get("Hide") as bool?;
    /// </summary>
    public bool Hide => _item.Bool("Hide");

    /// <summary>
    /// HorizontalAlignment as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("HorizontalAlignment", scrubHtml: true) etc.
    /// </summary>
    public string HorizontalAlignment => _item.String("HorizontalAlignment", fallback: "");

    /// <summary>
    /// LinkParameters as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LinkParameters", scrubHtml: true) etc.
    /// </summary>
    public string LinkParameters => _item.String("LinkParameters", fallback: "");

    /// <summary>
    /// LinkTarget as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LinkTarget", scrubHtml: true) etc.
    /// </summary>
    public string LinkTarget => _item.String("LinkTarget", fallback: "");

    /// <summary>
    /// LinkType as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LinkType", scrubHtml: true) etc.
    /// </summary>
    public string LinkType => _item.String("LinkType", fallback: "");

    /// <summary>
    /// LinkUrl as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("LinkUrl")
    /// </summary>
    public string LinkUrl => _item.Url("LinkUrl");

    /// <summary>
    /// Get the file object for LinkUrl - or null if it's empty or not referencing a file.
    /// </summary>

    [JsonIgnore]
    public IFile LinkUrlFile => _item.File("LinkUrl");

    /// <summary>
    /// Get the folder object for LinkUrl.
    /// </summary>

    [JsonIgnore]
    public IFolder LinkUrlFolder => _item.Folder("LinkUrl");

    /// <summary>
    /// LinkViewId as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LinkViewId", scrubHtml: true) etc.
    /// </summary>
    public string LinkViewId => _item.String("LinkViewId", fallback: "");

    /// <summary>
    /// LinkViewRef as single item of RadminDetails.
    /// </summary>
    /// <remarks>
    /// Generated to only return 1 child because field settings had Multi-Value=false. The type RadminDetails was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// A single item OR null if nothing found, so you can use ?? to provide alternate objects.
    /// </returns>
    public RadminDetails LinkViewRef => _linkViewRef ??= _item.Child<RadminDetails>("LinkViewRef");
    private RadminDetails _linkViewRef;

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");

    /// <summary>
    /// Width as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Width", scrubHtml: true) etc.
    /// </summary>
    public string Width => _item.String("Width", fallback: "");
  }
}